
const FRIEND_COUNT = 100;
const PAINTER_COUNT = 3;
const FRICTION = 0.99;
const COLOR = undefined;

let CONFIG = {
	FRIEND_COUNT: FRIEND_COUNT,
	PAINTER_COUNT: PAINTER_COUNT,
	FRICTION: FRICTION,
	COLOR: COLOR
};

export default CONFIG;